const CommandList = Object.freeze({
    START_SUBSCRIPTION: 'START_SUBSCRIPTION',
    ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
    ADD_TOPUP: 'ADD_TOPUP',
    PRINT_RENEWAL_DETAILS: 'PRINT_RENEWAL_DETAILS'
});

module.exports = CommandList;