// Index
const ZERO = 0;

// Devices
const TEN_DEVICE_PRICE = 100;
const FOUR_DEVICE_PRICE = 50;

// Subscription
const MUSIC_SUBSCRIPTION_FREE_PLAN_PRICE= 0;
const MUSIC_SUBSCRIPTION_FREE_PLAN_VALIDITY= 1;
const MUSIC_SUBSCRIPTION_PERSONAL_PLAN_PRICE= 100;
const MUSIC_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY= 1;
const MUSIC_SUBSCRIPTION_PREMIUM_PLAN_PRICE= 250;
const MUSIC_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY= 3;
const VIDEO_SUBSCRIPTION_FREE_PLAN_PRICE= 0;
const VIDEO_SUBSCRIPTION_FREE_PLAN_VALIDITY= 1;
const VIDEO_SUBSCRIPTION_PERSONAL_PLAN_PRICE= 200;
const VIDEO_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY= 1;
const VIDEO_SUBSCRIPTION_PREMIUM_PLAN_PRICE= 500;
const VIDEO_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY= 3;
const PODCAST_SUBSCRIPTION_FREE_PLAN_PRICE= 0;
const PODCAST_SUBSCRIPTION_FREE_PLAN_VALIDITY= 1;
const PODCAST_SUBSCRIPTION_PERSONAL_PLAN_PRICE= 100;
const PODCAST_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY= 1;
const PODCAST_SUBSCRIPTION_PREMIUM_PLAN_PRICE= 300;
const PODCAST_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY= 3;

const NO_OF_DAYS_BEFORE_TO_NOTIFIED = 10;

// Error Constants
const NO_COMMAND_FOUND = "No Command Found";
const INVALID_DEVICE = "Device is not valid";
const INVALID_SUBSCRIPTION_CATEGORY = "Subscription Category is invalid";
const INVALID_SUBSCRIPTION_PLAN = "Subscription Plan is invalid";
const ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED";
const ADD_TOPUP_FAILED = "ADD_TOPUP_FAILED";
const SUBSCRIPTIONS_NOT_FOUND = "SUBSCRIPTIONS_NOT_FOUND";
const INVALID_DATE = "INVALID_DATE";
const DUPLICATE_CATEGORY = "DUPLICATE_CATEGORY";
const DUPLICATE_TOPUP = "DUPLICATE_TOPUP";
const FILE_NOT_FOUND = "File not found";

// Final Output Constants
const RENEWAL_AMOUNT = "RENEWAL_AMOUNT";
const RENEWAL_REMINDER = "RENEWAL_REMINDER";

// Date constants
const INPUT_DATE_FORMAT = /^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$/;
const INPUT_DATE_STRING_SEPARATOR = "-";
const OUTPUT_DATE_LANG = "en-GB";
const OUTPUT_DATE_FORMAT = { day: '2-digit', month: '2-digit', year: 'numeric' };

module.exports = {
    ZERO,
    NO_OF_DAYS_BEFORE_TO_NOTIFIED,
    TEN_DEVICE_PRICE,
    FOUR_DEVICE_PRICE,
    MUSIC_SUBSCRIPTION_FREE_PLAN_PRICE,
    MUSIC_SUBSCRIPTION_FREE_PLAN_VALIDITY,
    MUSIC_SUBSCRIPTION_PERSONAL_PLAN_PRICE,
    MUSIC_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY,
    MUSIC_SUBSCRIPTION_PREMIUM_PLAN_PRICE,
    MUSIC_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY,
    VIDEO_SUBSCRIPTION_FREE_PLAN_PRICE,
    VIDEO_SUBSCRIPTION_FREE_PLAN_VALIDITY,
    VIDEO_SUBSCRIPTION_PERSONAL_PLAN_PRICE,
    VIDEO_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY,
    VIDEO_SUBSCRIPTION_PREMIUM_PLAN_PRICE,
    VIDEO_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY,
    PODCAST_SUBSCRIPTION_FREE_PLAN_PRICE,
    PODCAST_SUBSCRIPTION_FREE_PLAN_VALIDITY,
    PODCAST_SUBSCRIPTION_PERSONAL_PLAN_PRICE,
    PODCAST_SUBSCRIPTION_PERSONAL_PLAN_VALIDITY,
    PODCAST_SUBSCRIPTION_PREMIUM_PLAN_PRICE,
    PODCAST_SUBSCRIPTION_PREMIUM_PLAN_VALIDITY,
    NO_COMMAND_FOUND,
    SUBSCRIPTIONS_NOT_FOUND,
    ADD_SUBSCRIPTION_FAILED,
    ADD_TOPUP_FAILED,
    INVALID_DATE,
    DUPLICATE_CATEGORY,
    DUPLICATE_TOPUP,
    INVALID_SUBSCRIPTION_CATEGORY,
    INVALID_SUBSCRIPTION_PLAN,
    FILE_NOT_FOUND,
    INVALID_DEVICE,
    RENEWAL_AMOUNT,
    RENEWAL_REMINDER,
    INPUT_DATE_FORMAT,
    INPUT_DATE_STRING_SEPARATOR,
    OUTPUT_DATE_FORMAT,
    OUTPUT_DATE_LANG
};